"""
Ingests SYNTHETIC events to calibrate Snake Line — NOT to train the ML
classifier.

Inserted with `is_synthetic=True`, and `ml/train.py::_load_events_index()`
excludes them from the training set: they were generated by applying the
Snake Line heuristic itself to historical rain, so training/validating the
model with them would be circular contamination (the model would learn the
generation rule, not real terrain behavior).

Strategy: for each commune with historical rain coverage (6, 15, 16, 18,
21), selects days where SWI + rain_60min would have crossed Snake Line's
critical line. Creates a fictional but plausible LandslideEvent for that
date/commune.

Usage:

    cd platform/backend && PYTHONPATH=. python -m scraper.ingest_synthetic_events
"""

from __future__ import annotations

import asyncio
import json
from collections import defaultdict
from datetime import date, datetime, timedelta

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from alerts.snake_line import classify_point
from db.models.landslide_event import LandslideEvent
from db.models.ml_feature import MLFeature
from db.session import AsyncSessionLocal
from ml.soil_water_index import DRAIN_RATE_DEFAULT, compute_swi

# Communes with historical rain coverage (computed in a prior step)
COVERED_COMMUNES = {"6", "15", "16", "18", "21"}
DRAIN_RATE = DRAIN_RATE_DEFAULT  # 0.15
SWI_LOOKBACK_DAYS = 30


async def main() -> None:
    """Generate and insert synthetic Snake Line landslide events per covered commune."""
    async with AsyncSessionLocal() as session:
        # 1. Load historical daily rain per commune
        daily_rain_by_commune = await _load_daily_rain_by_commune(session)

        # 2. For each covered commune, find high-risk days
        synthetic_events = []
        for cid in sorted(COVERED_COMMUNES):
            if cid not in daily_rain_by_commune:
                continue

            daily_rain = daily_rain_by_commune[cid]
            events_for_cid = _find_high_risk_days(cid, daily_rain)
            synthetic_events.extend(events_for_cid)

        # 3. Check they don't already exist (by source_row_id)
        existing = set(
            await session.scalars(
                select(LandslideEvent.source_row_id).where(
                    LandslideEvent.source_row_id.like("synthetic:%")
                )
            )
        )

        # 4. Insert new synthetic events
        inserted = 0
        for ev in synthetic_events:
            if ev["source_row_id"] in existing:
                continue
            session.add(
                LandslideEvent(
                    source_row_id=ev["source_row_id"],
                    fecha=ev["fecha"].isoformat(),
                    tipo_emergencia=ev["tipo_emergencia"],
                    commune_id=ev["commune_id"],
                    barrio=None,
                    latitud=None,
                    longitud=None,
                    has_coords=False,
                    is_synthetic=True,
                )
            )
            inserted += 1

        await session.commit()

        print(
            json.dumps(
                {
                    "n_covered_communes": len(COVERED_COMMUNES),
                    "synthetic_events_found": len(synthetic_events),
                    "synthetic_events_inserted": inserted,
                    "communes": sorted(COVERED_COMMUNES),
                }
            )
        )


async def _load_daily_rain_by_commune(
    session: AsyncSession,
) -> dict[str, dict[date, float]]:
    """Loads historical daily rain (historical_siata, historical_ideam sources)."""
    from sqlalchemy import Float, cast

    stmt = (
        select(
            MLFeature.commune_id,
            func.date(MLFeature.reference_date),
            func.sum(cast(MLFeature.features["precip_sum_mm_day"].astext, Float)),
        )
        .where(
            MLFeature.features["source"].astext.in_(["historical_siata", "historical_ideam"]),
            MLFeature.reference_date.isnot(None),
        )
        .group_by(MLFeature.commune_id, func.date(MLFeature.reference_date))
    )

    rows = await session.execute(stmt)
    result: dict[str, dict[date, float]] = defaultdict(dict)
    for row in rows.all():
        cid = str(row[0]) if row[0] is not None else None
        d = row[1]
        precip = float(row[2]) if row[2] is not None else 0.0
        if cid is None or d is None:
            continue
        d = d.date() if isinstance(d, datetime) else d
        result[cid][d] = result[cid].get(d, 0.0) + precip

    return result


def _find_high_risk_days(commune_id: str, daily_rain: dict[date, float]) -> list[dict]:
    """Finds days where SWI + rain would have classified as ROJO/AMARILLO.
    Returns a list of dicts for LandslideEvent.
    """
    events = []

    # Search a far-enough-back window (2 years back) to be credible
    today = date.today()
    search_end = today - timedelta(days=365)  # a year ago
    search_start = search_end - timedelta(days=365 * 3)  # 3 years before that

    for d in sorted(daily_rain.keys()):
        if d < search_start or d > search_end:
            continue

        swi = compute_swi(daily_rain, d, drain_rate=DRAIN_RATE, window_days=SWI_LOOKBACK_DAYS)
        rain_mm = daily_rain.get(d, 0.0)

        status = classify_point(swi, rain_mm, commune_id)

        # Only keep ROJO or AMARILLO
        if status not in ("ROJO", "AMARILLO"):
            continue

        # Avoid too many consecutive events (hurts plausibility)
        if events and (d - events[-1]["fecha"]).days < 7:
            continue

        events.append(
            {
                "source_row_id": f"synthetic:snake_line:{commune_id}:{d.isoformat()}",
                "fecha": d,
                "commune_id": commune_id,
                "tipo_emergencia": f"Evento simulado — SWI={swi:.0f}%, lluvia={rain_mm:.1f}mm, status={status}",
            }
        )

    return events


if __name__ == "__main__":
    asyncio.run(main())
