"""initial_schema

Revision ID: b791d657baae
Revises: 
Create Date: 2026-04-22 19:36:25.513636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b791d657baae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_session_id'), 'agent_conversations', ['session_id'], unique=False)
    op.create_table('landslide_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_row_id', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Text(), nullable=True),
    sa.Column('tipo_emergencia', sa.Text(), nullable=True),
    sa.Column('commune_id', sa.String(length=64), nullable=True),
    sa.Column('barrio', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('has_coords', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landslide_events_commune_id'), 'landslide_events', ['commune_id'], unique=False)
    op.create_table('ml_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commune_id', sa.String(length=64), nullable=False),
    sa.Column('reference_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('precip_acum_7d', sa.Float(), nullable=True),
    sa.Column('n_events_window', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_features_commune_id'), 'ml_features', ['commune_id'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commune_id', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_commune_id'), 'risk_predictions', ['commune_id'], unique=False)
    op.create_table('scraping_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_downloaded', sa.Integer(), nullable=True),
    sa.Column('records_valid', sa.Integer(), nullable=True),
    sa.Column('records_discarded', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_risk_predictions_commune_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_ml_features_commune_id'), table_name='ml_features')
    op.drop_table('ml_features')
    op.drop_index(op.f('ix_landslide_events_commune_id'), table_name='landslide_events')
    op.drop_table('landslide_events')
    op.drop_index(op.f('ix_agent_conversations_session_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###
