"""
Landslide hazard = **susceptibility × trigger**. Pure, no I/O.

## Why this replaces the classifier

TEYVA has no usable supervised labels (verified 2026-07-29): of 5,880 real
events in `landslide_events`, 5,844 have no location at all, and the 36 with
a commune are mostly municipal press headlines, not landslides. The 26
positives the production model trained on came from the 144 **synthetic**
events generated by the Snake Line; once correctly filtered by
`is_synthetic`, the labels disappeared.

A classifier with no target isn't a classifier. What's defensible with the
data that does exist is the standard hazard formulation:

    hazard = susceptibility (terrain, static) × trigger (rain/seismic, dynamic)

Weights are **declared and documented**, not learned. With 26 positives —
and now 0 — learning 5 weights is fitting noise. A declared index is
auditable, explainable to Gestión del Riesgo, and recalibratable the day a
real inventory exists.

## Boundary with `domain/risk_rules.py`

`risk_rules` is the THRESHOLD layer: converts a score into a category and an
operational state. This module produces the score. No overlap: there's no
alert threshold here, and no hazard is computed there.

## Honesty about calibration

**No number in this module is calibrated against observed landslides.**
They come from literature and expert judgment, same as
`DRAIN_RATE_DEFAULT` in `ml/soil_water_index.py`. `risk_rules`'s thresholds
(0.35 / 0.65 / 0.90) were set for a classifier's probability, so applying
them to this index is a decision of operational continuity, not a proven
equivalence. It's declared in `CALIBRATION_STATUS` so it surfaces in the API
and the dashboard, not hidden in a comment.
"""

from __future__ import annotations

import unicodedata
from dataclasses import dataclass

CALIBRATION_STATUS = "no_calibrado"
CALIBRATION_NOTE = (
    "Pesos y rangos de normalización derivados de literatura y juicio experto, "
    "no ajustados contra deslizamientos observados en Medellín. Recalibrar cuando "
    "exista un inventario de eventos con fecha y ubicación (≥100 eventos reales)."
)

# ── Susceptibility weights (sum to 1.0) ───────────────────────────────────────
#
# If a component is missing, weights are RENORMALIZED over the ones available.
# This is essential, not a detail: today only `hazard_grade` is populated
# (GeoMedellín's VM_05, 401 barrios), and slope/TWI/NDVI arrive once SRTM and
# MODIS are ingested. Without renormalizing, an index with 4 of 5 components
# missing would read ~0.25 and look "not very susceptible" when it actually
# means "we don't know".
W_SLOPE = 0.30  # primary control on a slope's stability
W_HAZARD = 0.25  # official VM_05 hazard grade: already validated by geologists, don't discard it
W_TWI = 0.20  # where water accumulates
W_PRIOR = 0.15  # "dangerous zones repeat"
W_NDVI = 0.10  # less vegetation → fewer roots → less cohesion

# ── Normalization ranges ───────────────────────────────────────────────────────
# Slope: below 10° landslides are rare; above 45° loose material no longer
# holds, so it saturates.
SLOPE_MIN_DEG = 10.0
SLOPE_MAX_DEG = 45.0
# TWI: dimensionless. Low values = dry divides; high values = valleys where
# flow converges.
TWI_MIN = 3.0
TWI_MAX = 15.0
# Minimum NDVI: ~0.8 is dense vegetation, ~0.1 is bare soil. INVERTED.
NDVI_DENSE = 0.8
NDVI_BARE = 0.1
# Prior event density: saturates fast — the difference between 0 and 2 events
# is far more informative than between 8 and 10.
PRIOR_SATURATION = 4.0

# VM_05 hazard grade → 0-1. "Muy alta" exists in some POT layers. Keys match
# GeoMedellín's Spanish-language source data verbatim.
_HAZARD_SCORES: dict[str, float] = {
    "muy alta": 1.0,
    "alta": 0.85,
    "media": 0.5,
    "moderada": 0.5,
    "baja": 0.15,
    "muy baja": 0.05,
    "sin amenaza": 0.0,
}


def _strip_accents(text: str) -> str:
    nkfd = unicodedata.normalize("NFD", text.strip().lower())
    return "".join(c for c in nkfd if unicodedata.category(c) != "Mn")


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def _normalize_range(value: float | None, low: float, high: float) -> float | None:
    """Maps `value` to 0-1 within [low, high], saturating at the extremes."""
    if value is None:
        return None
    if high == low:
        return None
    return _clamp01((value - low) / (high - low))


def normalize_slope(slope_deg: float | None) -> float | None:
    return _normalize_range(slope_deg, SLOPE_MIN_DEG, SLOPE_MAX_DEG)


def normalize_twi(twi: float | None) -> float | None:
    return _normalize_range(twi, TWI_MIN, TWI_MAX)


def normalize_ndvi(ndvi_min: float | None) -> float | None:
    """NDVI → susceptibility. Inverted: less vegetation, more susceptible."""
    if ndvi_min is None:
        return None
    return _normalize_range(-ndvi_min, -NDVI_DENSE, -NDVI_BARE)


def normalize_hazard_grade(grade: str | None) -> float | None:
    """VM_05 text grade → 0-1. Unknown grade → None, never 0.0.

    Returning 0.0 for unrecognized text would say "no hazard", the opposite
    of "I don't have the data".
    """
    if not grade or not grade.strip():
        return None
    key = _strip_accents(grade)
    if key in _HAZARD_SCORES:
        return _HAZARD_SCORES[key]
    # Partial match: the layer sometimes carries "Amenaza alta por movimientos…".
    # Tried most-specific to least so "muy alta" doesn't match on "alta".
    for label in sorted(_HAZARD_SCORES, key=len, reverse=True):
        if label in key:
            return _HAZARD_SCORES[label]
    return None


def normalize_prior_events(n_events: float | None) -> float | None:
    """Number of inventoried historical landslides → 0-1, saturating.

    ⚠️ The caller must count ONLY events prior to the reference date and
    exclude synthetic ones. A supervised model's label IS an event, so using
    the full history would leak the target. This can't be checked here: it's
    a contract on the caller.
    """
    if n_events is None:
        return None
    if n_events <= 0:
        return 0.0
    return _clamp01(1.0 - 0.5 ** (n_events / PRIOR_SATURATION))


@dataclass(frozen=True)
class SusceptibilityBreakdown:
    """Index and its breakdown, so the dashboard can show it as auditable.

    `coverage` is the fraction of weight that actually had data: an index
    with coverage 0.25 is a guess, not a measurement, and the UI needs to be
    able to say so.
    """

    index: float | None
    components: dict[str, float | None]
    weights_used: dict[str, float]
    coverage: float


_COMPONENT_WEIGHTS: tuple[tuple[str, float], ...] = (
    ("slope", W_SLOPE),
    ("hazard", W_HAZARD),
    ("twi", W_TWI),
    ("prior", W_PRIOR),
    ("ndvi", W_NDVI),
)


def susceptibility_breakdown(
    *,
    slope_p90_deg: float | None = None,
    twi_p90: float | None = None,
    ndvi_min: float | None = None,
    hazard_grade: str | None = None,
    hazard_fraction: float | None = None,
    prior_event_count: float | None = None,
) -> SusceptibilityBreakdown:
    """Static susceptibility 0-1, with breakdown and coverage.

    Weights are renormalized over the components present, so the index is
    comparable across zones even when some have more data than others — but
    `coverage` says how much confidence it deserves.

    The hazard component accepts two forms, and `hazard_fraction` takes
    priority because it's a better signal:

    - `hazard_fraction` (0-1): fraction of the area in high hazard,
      aggregated over many polygons (e.g. a commune's barrios).
    - `hazard_grade` (text): the VM_05 grade at ONE point. The fallback when
      there's no disaggregation. Careful: sampling at the centroid is
      misleading — commune 1 (Popular, northeastern hillside) comes out
      "Baja" at its centroid while 3 of its 12 barrios are in Alta hazard.
    """
    components: dict[str, float | None] = {
        "slope": normalize_slope(slope_p90_deg),
        "hazard": (
            _clamp01(hazard_fraction)
            if hazard_fraction is not None
            else normalize_hazard_grade(hazard_grade)
        ),
        "twi": normalize_twi(twi_p90),
        "prior": normalize_prior_events(prior_event_count),
        "ndvi": normalize_ndvi(ndvi_min),
    }

    total_weight = 0.0
    weighted_sum = 0.0
    weights_used: dict[str, float] = {}
    for name, weight in _COMPONENT_WEIGHTS:
        value = components[name]
        if value is None:
            continue
        weights_used[name] = weight
        total_weight += weight
        weighted_sum += weight * value

    if total_weight <= 0.0:
        return SusceptibilityBreakdown(None, components, {}, 0.0)

    index = _clamp01(weighted_sum / total_weight)
    # The weights reported are the EFFECTIVE ones (already renormalized) —
    # what a tooltip needs to show so the sum adds up.
    effective = {k: round(w / total_weight, 4) for k, w in weights_used.items()}
    return SusceptibilityBreakdown(
        index=round(index, 4),
        components=components,
        weights_used=effective,
        coverage=round(total_weight, 4),
    )


def susceptibility_index(**kwargs: float | str | None) -> float | None:
    """Shortcut for when only the scalar is needed."""
    return susceptibility_breakdown(**kwargs).index  # type: ignore[arg-type]


# ── Trigger (dynamic) ──────────────────────────────────────────────────────────
#
# SWI already comes in 0-100%, so it's divided. The antecedent rain index is
# in mm with no natural ceiling: normalized against the reference declared in
# `risk_rules.ANTECEDENT_INDEX_THRESHOLD_MM`, which the caller passes in.
SEISMIC_SATURATION = 30.0  # Σ mag²·attenuation·decay considered "high"

# Seismic activity MODULATES, it doesn't trigger on its own: in Medellín the
# dominant trigger is rain. A quake on dry soil rarely moves a slope; on
# saturated soil it does. So the trigger is rain enhanced by seismicity, not
# an average of the two.
SEISMIC_MAX_BOOST = 0.35


def trigger_breakdown(
    *,
    soil_water_index_pct: float | None = None,
    antecedent_precip_mm: float | None = None,
    antecedent_reference_mm: float = 100.0,
    seismic_intensity: float | None = None,
) -> dict[str, float | None]:
    """Trigger 0-1 and its parts.

    Rain = max(SWI, normalized antecedent index) — the max is taken, not the
    mean, because they're two ways of measuring the same thing (accumulated
    soil water) and averaging them would dilute a high signal with a low one.
    """
    swi = _clamp01(soil_water_index_pct / 100.0) if soil_water_index_pct is not None else None
    api = (
        _clamp01(antecedent_precip_mm / antecedent_reference_mm)
        if antecedent_precip_mm is not None and antecedent_reference_mm > 0
        else None
    )
    seismic = (
        _clamp01(seismic_intensity / SEISMIC_SATURATION) if seismic_intensity is not None else None
    )

    rain_parts = [v for v in (swi, api) if v is not None]
    rain = max(rain_parts) if rain_parts else None

    if rain is None:
        trigger = None
    else:
        boost = 1.0 + SEISMIC_MAX_BOOST * (seismic or 0.0)
        trigger = _clamp01(rain * boost)

    return {
        "trigger": round(trigger, 4) if trigger is not None else None,
        "rain": round(rain, 4) if rain is not None else None,
        "swi": swi,
        "antecedent": round(api, 4) if api is not None else None,
        "seismic": round(seismic, 4) if seismic is not None else None,
    }


def hazard_score(susceptibility: float | None, trigger: float | None) -> float | None:
    """Hazard 0-1 = GEOMETRIC mean of susceptibility and trigger.

    Geometric mean, not product: the product of two 0-1 values compresses
    toward zero (0.5 × 0.5 = 0.25), so with the current thresholds
    (medium 0.35 / high 0.65 / critical 0.90) "critico" would almost never be
    reached and the index would be useless in practice. The geometric mean
    preserves scale (0.5 and 0.5 → 0.5) while keeping the physical property
    that matters: if EITHER factor is zero, the hazard is zero. No trigger,
    no landslide; on flat, stable terrain, also none.

    Returns None if either input is missing: a made-up score is worse than
    no score at all, especially if it feeds an alert to Gestión del Riesgo.
    """
    if susceptibility is None or trigger is None:
        return None
    return round((max(0.0, susceptibility) * max(0.0, trigger)) ** 0.5, 4)
