"""
Assembles per-commune hazard from the DB: susceptibility × trigger.

Replaces the supervised classifier as the source of `risk_score`. The
reason is in `domain/susceptibility.py`: TEYVA has no usable labels, and
the 26 positives the production model trained on came from synthetic
events generated by the Snake Line.

This module is the I/O; the formula and weights are pure and live in
`domain/susceptibility.py`. Follows the same pattern as its neighbors
(`ml/precip_index.py`, `ml/soil_water_index.py`, `ml/seismic_features.py`):
one `*_by_commune(session)` function that resolves all 21 communes in a
single pass.

**Computing all 21 at once isn't an optimization, it's the design.** The
underlying functions already aggregate by commune in one query; calling
them per commune inside `run_predictions`'s loop would multiply DB work by
21. That's why `predict_risk` accepts a precomputed bundle.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import date
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from db.models.ml_feature import MLFeature
from domain.communes import COMMUNES
from domain.risk_rules import ANTECEDENT_INDEX_THRESHOLD_MM
from domain.susceptibility import (
    CALIBRATION_NOTE,
    CALIBRATION_STATUS,
    hazard_score,
    susceptibility_breakdown,
    trigger_breakdown,
)

logger = logging.getLogger(__name__)

# VM_05 grade sampled at the commune's centroid, written by
# `scraper/medellin_datos.py`.
CENTROID_HAZARD_KEY = "geomorf_riesgo_grado_amenaza"


@dataclass(frozen=True)
class CommuneHazard:
    """A commune's hazard, with everything needed to audit it."""

    commune_id: str
    score: float | None
    susceptibility: float | None
    trigger: float | None
    susceptibility_components: dict[str, float | None] = field(default_factory=dict)
    susceptibility_weights: dict[str, float] = field(default_factory=dict)
    susceptibility_coverage: float = 0.0
    trigger_components: dict[str, float | None] = field(default_factory=dict)
    # "barrios" (~269-polygon aggregate) | "centroide" (one point) | None.
    hazard_source: str | None = None
    reason: str | None = None

    def as_dict(self) -> dict[str, Any]:
        """Serializes to a plain dict for API/JSON responses."""
        return {
            "score": self.score,
            "susceptibility": self.susceptibility,
            "trigger": self.trigger,
            "susceptibility_components": self.susceptibility_components,
            "susceptibility_weights": self.susceptibility_weights,
            "susceptibility_coverage": self.susceptibility_coverage,
            "trigger_components": self.trigger_components,
            "hazard_source": self.hazard_source,
            "calibration": CALIBRATION_STATUS,
            "calibration_note": CALIBRATION_NOTE,
            "reason": self.reason,
        }


async def _centroid_hazard_grades(session: AsyncSession) -> dict[str, str]:
    """VM_05 grade at each commune's centroid, most recent row first.

    Fallback for communes with no barrio-level disaggregation: today the 5
    corregimientos (ids 17-21), which don't appear in
    `platform/frontend/lib/barrios-medellin.json` and thus aren't in
    `barrio_hazard` — precisely the 5 territories that are all hillside.
    """
    stmt = (
        select(MLFeature.commune_id, MLFeature.features)
        .where(MLFeature.features.isnot(None))
        .order_by(MLFeature.reference_date.desc().nulls_last())
    )
    out: dict[str, str] = {}
    for commune_id, features in (await session.execute(stmt)).all():
        cid = str(commune_id)
        if cid in out or not isinstance(features, dict):
            continue
        grade = features.get(CENTROID_HAZARD_KEY)
        if isinstance(grade, str) and grade.strip():
            out[cid] = grade
    return out


async def _safe(label: str, coro: Any, default: Any) -> Any:
    """Runs one data source without letting its failure take down the rest.

    Same criterion as `scraper/siata.py`: a downed feature family degrades
    the index, it doesn't abort it. The degradation shows up in `coverage`,
    so it's data, not just a log line.
    """
    try:
        return await coro
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not compute %s: %s", label, exc)
        return default


async def hazard_by_commune(
    session: AsyncSession, *, as_of: date | None = None
) -> dict[str, CommuneHazard]:
    """Hazard for all 21 communes in a single pass."""
    from ml.barrio_hazard_features import pct_barrios_alta_amenaza
    from ml.precip_index import antecedent_indexes_for_all_communes
    from ml.seismic_features import seismic_intensity_by_commune
    from ml.soil_water_index import swi_for_all_communes

    hazard_frac: dict[str, float] = await _safe(
        "barrio hazard", pct_barrios_alta_amenaza(session), {}
    )
    centroid_grades: dict[str, str] = await _safe(
        "centroid hazard", _centroid_hazard_grades(session), {}
    )
    swi: dict[str, float] = await _safe(
        "soil water index", swi_for_all_communes(session, as_of), {}
    )
    api: dict[str, float] = await _safe(
        "antecedent rain index", antecedent_indexes_for_all_communes(session, as_of), {}
    )
    seismic: dict[str, float] = await _safe(
        "seismic intensity", seismic_intensity_by_commune(session), {}
    )
    seismic_default = seismic.get("_default")

    out: dict[str, CommuneHazard] = {}
    for commune in COMMUNES:
        cid = commune.id

        # Barrios aggregate ~269 polygons; the centroid is ONE point and is
        # misleading (commune 1 comes out "Baja" at its centroid with 3 of
        # 12 barrios in Alta). That's why barrios take priority, and what
        # was used gets recorded.
        frac = hazard_frac.get(cid)
        if frac is not None:
            hazard_source: str | None = "barrios"
        elif cid in centroid_grades:
            hazard_source = "centroide"
        else:
            hazard_source = None

        susc = susceptibility_breakdown(
            hazard_fraction=frac,
            hazard_grade=centroid_grades.get(cid) if frac is None else None,
            # Slope, TWI and NDVI arrive once SRTM and MODIS are ingested
            # (`scraper/terrain_features.py`); `prior_event_count`, with SIMMA.
            # Absent, the weights get renormalized over what's available.
        )
        trig = trigger_breakdown(
            soil_water_index_pct=swi.get(cid),
            antecedent_precip_mm=api.get(cid),
            antecedent_reference_mm=ANTECEDENT_INDEX_THRESHOLD_MM,
            seismic_intensity=seismic.get(cid, seismic_default),
        )

        score = hazard_score(susc.index, trig["trigger"])
        reason = None
        if score is None:
            faltan = []
            if susc.index is None:
                faltan.append("susceptibilidad (sin amenaza VM_05)")
            if trig["trigger"] is None:
                faltan.append("disparador (sin lluvia reciente)")
            reason = "sin datos de " + " ni ".join(faltan)

        out[cid] = CommuneHazard(
            commune_id=cid,
            score=score,
            susceptibility=susc.index,
            trigger=trig["trigger"],
            susceptibility_components=susc.components,
            susceptibility_weights=susc.weights_used,
            susceptibility_coverage=susc.coverage,
            trigger_components=trig,
            hazard_source=hazard_source,
            reason=reason,
        )
    return out


async def hazard_for_commune(
    session: AsyncSession, commune_id: str, *, as_of: date | None = None
) -> CommuneHazard:
    """Hazard for ONE commune. Computes all 21 under the hood (the queries
    aggregate by commune anyway); for a batch use `hazard_by_commune`."""
    everything = await hazard_by_commune(session, as_of=as_of)
    return everything.get(
        str(commune_id),
        CommuneHazard(
            commune_id=str(commune_id),
            score=None,
            susceptibility=None,
            trigger=None,
            reason=f"comuna {commune_id} no está en domain/communes.py",
        ),
    )
